author_id = "demo"
app_id = "firefly-bitsy"
author_name = "Demo"
app_name = "Firefly Bitsy"

[files]
main = { path = "main.bitsy.txt", copy = true, url = "https://raw.githubusercontent.com/Ragzouken/bitsy-archive/refs/heads/main/1F6683A4.bitsy.txt" }
font = { path = "eg_6x9.fff", url = "https://fonts.fireflyzero.com/fonts/ascii/eg_6x9.fff" }
